- name: pypi-publish
  if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
  uses: pypa/gh-action-pypi-publish@v1.4.1
  with:
    user: __token__
    password: ${{ secrets.PYPI_API_TOKEN }}
    repository_url: https://test.pypi.org/legacy/
